F/cluster function split
capitalone/global-attribution-mapping pull request #33
Opened 2020-11-20 18:11 UTC by tazitoo

Updated:
1) clustering API - allows users to use external routine
2) internal clustering routines: build & fastPAM for exhaustive search on smaller datasets, banditPAM for approximate search on large datasets, scales like O(nlogn)
3) some clustering example scripts - useful test cases, might be useful for longer running tests

2020-11-25 16:00 UTC, rreilly10 requested changes
This looks really great - straight forward and easy to understand. I do have a few requests and thoughts that I added in the comments below.

I had to install `numba` - we should put that in the `requirements.txt`
Looks like`numba==0.51.2` will work

Also, if you could install flake8 and run the `lint_local` command that would be great.
Looks like quite a few new linting issues were introduced that are breaking the pipeline.

```
pip install flake8
make lint_local
```

If there are any linting issues you see that you want to change we can also add those to the `.flake8` file

I'll submit a PR soon that will include all of the testing/linting dependencies, and a better contribution guide for what to run locally vs. what is run when a PR is opened

2020-12-21 15:58 UTC, tazitoo commented on tests/test_clustering.py
created a test from one of the clustering examples

2020-12-21 15:58 UTC, tazitoo commented on examples/clustering/cluster_700_9.py
> +#pca = PCA(n_components=2)
I think I cleaned up most of the commented code...

2020-12-21 16:14 UTC, tazitoo reviewed
I think all outstanding issues were cleaned up...

2021-01-05 16:12 UTC, rreilly10 requested changes
Looks great - just one more request for separate euclidian and spearman tests

2021-01-05 16:12 UTC, rreilly10 commented on tests/test_banditPAM.py
> +    # if testing with 'euclidean' distance
We could just create two tests to handle both of these. One for euclidian and one for spearman

2021-01-05 18:35 UTC, rreilly10 approved these changes

2021-01-05 18:36 UTC, merged