original banditpam cleanup PR
capitalone/global-attribution-mapping pull request #49
Opened 2021-03-22 01:35 UTC by markymarkdavis

I moved the code from the individual methods to the KMedoids class, updated the for loops, added documentation, and added batchsize as an optional parameter.

2021-03-31 14:45 UTC, Lazea requested changes
Left some comments, most around documentation. Also I recommend setting up `black` and `flake8` to help reformat some of the code.

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +            TODO: Update this
Forgot to update the output documentation here.

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +        """Inner loop for pam build and bandit build functions.
Inner loop for both `PAM` and `BanditPAM`? The name suggests this is for `Bandit` only.

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +            d_nearest (np.ndarray): The distances for all of the centers
Missing `td` parameter in the args here.

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +            d_nearest (np.ndarray): The distances for all of the centers
Looks like `td` is not being used below at all.

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +            sigma_x (np.ndarray): The confidence interval.
These are out of order, return is `sigma_x, `mu_x`.

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +            tol (float): [description]
Missing description.

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +            verbose (bool): Determining whether or not to print out updates
I think these two parameters should have default values.

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +                np.apply_along_axis(lambda a_swap: self._swap_pairs(X, d, a_swap, dist_func, idx_ref, n_used_ref, mu_x, sigma_x, D, E, Tih_min, "h"), 1, swap_pairs)
This line is kinda long, could you reformat it?

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +        """ Batch updates mu and sigma for bandit PAM using Welford's algorithm
What would the `mu` and `sigma` be in this function?

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +            lmbda = np.vectorize(lambda j: self._looping_solution_ids(X, idx_ref, dist_func, d_nearest, n_used_ref, mu_x, sigma_x, j, i), otypes="O")
Long line, reformat.

2021-03-31 14:45 UTC, Lazea commented on gam/clustering.py
> +            Tih = np.apply_along_axis(lambda a_swap: self._swap_pairs(X, d, a_swap, dist_func, idx_ref, n_used_ref, mu_x, sigma_x, D, E, Tih_min, "i"), 1, swap_pairs)
Long line, reformat.

2021-03-31 14:48 UTC, Lazea commented
Would be good to add the use of `bandit` method to the mushroom example notebook.

2021-03-31 18:59 UTC, Lazea approved these changes
LGTM

2021-04-08 13:10 UTC, rreilly10 approved these changes

2021-04-08 13:12 UTC, merged